"colorscheme desert 
colorscheme evening
set cpo&vim 
set background=dark 
set backspace=indent,eol,start 
set backup 
set diffexpr=MyDiff() 
set guifont=Cascadia_Mono_PL:h14:cANSI 
set helplang=En 
set history=50 
set hlsearch 
set incsearch 
set keymodel=startsel,stopsel 
set ruler 
set selection=exclusive 
set selectmode=mouse,key 
set whichwrap=b,s,<,>,[,] 
set window=39 
set nu 
set tabstop=4 
set expandtab 
set shiftwidth=4 
set so=5 
set ff=unix
